### ISSUE TITLE
eTag headers not being set

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#140]
It looks like we're not setting etag headers when making PUT requests to the Agent profile API. This is preventing the plugin from working with LRSs that pass the ADL conformance test suite e.g. Watershed. 

![image](https://user-images.githubusercontent.com/1363163/28878177-63d517f4-7796-11e7-977a-4d80fe6deb50.png)

Relevant code is here: 

https://github.com/garemoko/moodle-mod_tincanlaunch/blob/e7799fd82e533c95ba9df7b9e083f6c5b613b32d/locallib.php#L332-L358

I'm not clear on whether this is an issue with TinCanPHP or the plugin. Either way, we need to be setting the If-None-Match header in cases where the document is not found. I.e. an else statement here: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/e7799fd82e533c95ba9df7b9e083f6c5b613b32d/locallib.php#L350

**Comment by garemoko** [comment]
Actually looks like a tincanphp issue https://github.com/RusticiSoftware/TinCanPHP/pull/90

**Comment by garemoko** [comment]
Fixed by https://github.com/RusticiSoftware/TinCanPHP/pull/90. 

Once that is merged we'll need to bump TinCanPHP and re-release.

**Comment by davidpesce** [comment]
Yea, this appears to be the same issue. I'll close the other.

That being said, I applied the fix here: RusticiSoftware/TinCanPHP#90 and it didn't resolve the issue for me. I can see the agentProfiles set up in the database, but get a 404 when trying to retrieve them via the API.

**Comment by garemoko** [comment]
"I can see the agentProfiles set up in the database" - you see the data stored?

**Comment by davidpesce** [comment]
Yes, I can see it stored in the DB when using the launch plugin content. But get a 404 when retrieving it via the launch plugin content.

If I set the agentProfile (basically an ID that I've deemed necessary) via postman, the content launches and plays fine.

**Comment by garemoko** [comment]
well thats weird. any difference between how its store when its stored by the plugin vs when its stored via postman?

**Comment by davidpesce** [comment]
That's what is really weird... The only difference I see is the order of the agent.name vs agent.mbox.

In the tcl_content version, the agent.name appears before the agent.mbox

In the postman version, the agent.mbox appears first.

Otherwise, they are identical (well minus etag values, and storage times)

**Comment by davidpesce** [comment]
Whoa, it appears that the order does matter. I deleted the version created by postman and modified the version created with tcl_content (directly via db). Course launches and retrieves fine. It does create another instance of the agentProfile (ID) that I'm retrieving as well. Something is still wonk. Not sure if this is LRS related or plugin related.

**Comment by davidpesce** [comment]
I'm not seeing anything in the spec that would dictate an order to those values. I think it's an LRS issue.

**Comment by garemoko** [comment]
Yeh, the order shouldn't matter

**Comment by garemoko** [comment]
Fixed in master. Will be in next release.
