### ISSUE TITLE
Defaults for settings

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#30]
There are a number of issues with default settings:

Within the plugin settings:

Version should be 1.0.1
Duration should be populated
Within the instance settings

Duration should take the global default
The verb id should be completed.

**Comment by davidpesce** [comment]
This should be resolved with PR #44.

**Comment by garemoko** [comment]
There's still an issue with the 'Track completion by verb' setting where if you save the module with the 'Do not indicate activity completion' setting and then change it to 'Show activity complete when conditions are met', the verb field defaults to empty.

**Comment by garemoko** [comment]
<s>We should also default to insecure authentication. </s> - done
